# webhost/mypath -> pod/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /mypath
        backend:
          serviceName: myservice
          servicePort: 8080
          
# webhost/mypath/abc => pod/abc
# webhost/mypath => pod/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: myingress
spec:
  rules:
  - host: www.abc.com
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 80
        path: /mypath(/|$)(.*)
          
